##  plot4.R
png("plot4.png")
par(mfrow=c(2,2))
plot(hpc$DateTime,hpc$Global_active_power, type="l", ylab="Global Active Power", xlab="")
plot(hpc$DateTime, hpc$Voltage ,xlab="datetime", type="l")
plot(hpc$DateTime,hpc$Sub_metering_1, type="l", ylab="Energy sub metering", xlab="")
lines(hpc$DateTime,hpc$Sub_metering_2, type="l", col="red")
lines(hpc$DateTime,hpc$Sub_metering_3, type="l", col="blue")
legend("topright", legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"), lwd=1, col=c("black","blue","red"))
plot(hpc$DateTime,hpc$Global_reactive_power, xlab="datetime", type="l", ylab="Global_reactive_power")
dev.off()